AppBundle\Entity\CorrectUserDatabase: 
  type: entity
  table: users
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields: 
    username:
      type: string
      length: 100
      column: username
    password:
      type: string
      length: 100    
      column: password
    role:
      type: string
      length: 20
      column: role  